# Service Parameters
data_dir: /opt/svc/collection_landsat/collection_landsat/resources/data
port: 8000
mysql:
  host:
  port:
  user:
  passwd:
  db:
# Data Paramters
google_api_url: 'http://storage.googleapis.com/earthengine-public/landsat/'
search_api_url: 'https://api.developmentseed.org/satellites/landsat'
